config/routes.rb
Rails.application.routes.draw do

  root 'feeds#index'

  resources :feeds, only: [:index]

  resources :projects, only: [:index, :show, :edit, :update]

  resources :plugins, only: [:show] do
    resources :versions, only: [:index, :show]
  end

  resources :cron_logs, only: [:index]

  resources :abouts, only: [:index]

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController

  # トップ画面 フィード一覧
  def index
    @rails_entries = Entry.rails_entries

    @search = Entry.newest_plugins.ransack(params[:q])
    @entries = @search.result.page(params[:page])

    # alert = Project.joins(:project_versions).where('project_versions.vulnerability' => true)
    # if alert.present?
    #   flash.now['alert'] = "脆弱性のあるgemが定義されたプロジェクトがあります"
    # end
  end

end

app/helpers/feeds_helper.rb
module FeedsHelper

  # 1週間以内の場合、Newラベルを表示する
  def new_label(date)
    if date > 1.weeks.ago
      content_tag(:span, class: "ui orange horizontal label") do
        'New'
      end
    end
  end

  # 3を超える場合...moreボタンを表示する
  def show_more(count ,path)
    if count > 3
      link_to(path, class: 'item') do
        content_tag(:div, class: "ui small label") do
          '...more'
        end
      end
    end
  end


end

app/views/feeds/index.html.erb
<!--<div class="ui two column centered grid"> -->
<div class="main ui container">
  <div class="row">
    <div class="column">

      <h2 class="ui header">
        Gem Release Feeds
        <span class="sub header">それぞれのGemの最新リリースフィードを表示しています。</span>
      </h2>

      <div class="ui segment">
        <div class="ui accordion">
          <div class="title active">
            <h3 class="ui header">
              Rails Release Feeds
            </h3>
          </div>
          <div class="content active">
            <table class="ui very basic table compact">
              <thead>
                <tr>
                <th>リリースタイトル(Version)</th>
                <th>更新日時</th>
                <th>更新可能なプロジェクト</th>
                <th>プロジェクトの脆弱性(未修正)情報</th>
                </tr>
              </thead>
              <tbody>
                <% @rails_entries.each do |entry| %>
                  <tr>
                    <td>
                      <%= new_label(entry.published) %>
                      <%= link_to entry.title,
                        plugin_version_path(plugin_id: entry.plugin.id, id: entry.id) %>
                    </td>
                    <td>
                      <%= l entry.published %>
                    </td>
                    <td>
                      <%# 更新可能なプロジェクトバージョンを取得 %>
                      <% versions = entry.updatable_project_versions_by_series(@rails_entries) %>
                      <% project_versions = versions.order_by_version %>
                      <% project_versions.includes(:project).limit(3).each do |v| %>
                        <%= link_to(project_path(v.project.id), class: 'item') do %>
                          <div class="ui mini label">
                            <%= v.project.name %> <%= v.installed %>
                          </div>
                        <% end %>
                      <% end %>
                      <%# 4件以上あればmoreボタン %>
                      <%= show_more(versions.count, plugin_version_path(plugin_id: entry.plugin.id, id: entry.id)) %>
                    </td>
                    <td>
                      <%# 脆弱性のある系列ごとのプロジェクトバージョン(重複なし)を取得 %>
                      <% alert_versions = versions.uniq_vulnerable_versions %>
                      <% alert_versions.each do |version|%>
                        <%= link_to plugin_version_path(plugin_id: entry.plugin.id, id: version.entry_id), class: 'ui mini label red' do %>
                            <i class="warning sign icon"></i> <%= version.installed %>
                        <% end %>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <div class="ui segment">
        <div class="ui form">
          <%= search_form_for @search, url: feeds_path do |f| %>
            <div class="inline fields">
              <div class="field">
                <%= f.text_field :plugin_name_start, placeholder: 'Gem Name', class: '' %>

                <%= f.check_box :plugin_project_versions_vulnerability_eq, class: 'ui' %>
                <%= f.label :plugin_project_versions_vulnerability_eq, 'プロジェクト脆弱性有' %>
              </div>
              <%= f.submit '検索', class: "ui olive button" %>
              <%= link_to 'クリア', feeds_path, class: 'ui button' %>
            </div>
          <% end %>
        </div>

        <table class="ui very basic table compact">
          <thead>
            <tr>
            <th>リリースタイトル(Version)</th>
            <th>更新日時</th>
            <th>更新可能なプロジェクト</th>
            <th>プロジェクトの脆弱性(未修正)情報</th>
            </tr>
          </thead>
          <tbody>
            <% @entries.each do |entry| %>
              <tr>
                <td>
                  <%= new_label(entry.published) %>
                  <%= link_to entry.title,
                      plugin_version_path(plugin_id: entry.plugin.id, id: entry.id) %>
                </td>
                <td>
                  <%= l entry.published %>
                </td>
                <td>
                  <%# 更新可能なプロジェクトバージョンを取得 %>
                  <% project_versions = entry.plugin.project_versions.updatable %>
                  <% project_versions.includes(:project).limit(3).each do |v| %>
                    <%= link_to(project_path(v.project.id), class: 'item') do %>
                      <div class="ui mini label">
                        <%= v.project.name %> <%= v.installed %>
                      </div>
                    <% end %>
                  <% end %>
                  <%# 4件以上あればmoreボタン %>
                  <%= show_more(project_versions.count, plugin_path(entry.plugin.id)) %>
                </td>
                <td>
                  <%# 脆弱性のあるプロジェクトバージョン(重複なし)を取得 %>
                  <% alert_versions = entry.plugin.project_versions.uniq_vulnerable_versions %>
                  <% alert_versions.each do |version|%>
                    <% if version %>
                      <%= link_to plugin_version_path(plugin_id: entry.plugin.id, id: version.entry.id), class: 'ui mini label red' do %>
                        <i class="warning sign icon"></i> <%= version.installed %>
                      <% end %>
                    <% end %>
                  <% end %>
                </td>
              </tr>

            <% end %>
          </tbody>
        </table>

        <p><%= page_entries_info @entries %></p>
        <%= paginate @entries %>
      </div>
    </div>
  </div>
</div>