config/routes.rb
Rails.application.routes.draw do

  root 'feeds#index'

  resources :feeds, only: [:index]

  resources :projects, only: [:index, :show, :edit, :update]

  resources :plugins, only: [:show] do
    resources :versions, only: [:index, :show]
  end

  resources :cron_logs, only: [:index]

  resources :abouts, only: [:index]

end

app/models/plugin.rb
# == Schema Information
#
# Table name: plugins
#
#  id              :integer          not null, primary key
#  name            :string
#  newest          :string
#  pre             :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  source_code_uri :string
#  homepage_uri    :string
#

class Plugin < ActiveRecord::Base
  has_many :project_versions
  has_many :projects, through: :project_versions
  has_many :entries, dependent: :destroy
  has_many :security_entries, dependent: :destroy
  has_many :security_advisories, dependent: :destroy

  has_many :dependencies, dependent: :nullify

  validates :name, presence: true
  # validates :name, length: { maximum: 50 }, allow_blank: true
  # validates :name, format: { with: /\A[a-z0-9\._-]+\z/i }, allow_blank: true

  # gem更新画面のみ
  #validates :source_code_uri, presence: true, on: :update
  # validates :source_code_uri, length: { maximum: 200 }, allow_blank: true
  # validates :source_code_uri, format: {
  #                               with: /\A#{URI::regexp(%w(http https))}\/\z/,
  #                               message: "はURL形式で入力して下さい。末尾は/で終了する必要があります。"
  #                             },
  #                             allow_blank: true

  #before_destroy :destroy_relatitons

  after_create  :create_created_table_log
  after_update  :create_updated_table_log
  after_destroy :create_destroyed_table_log


  scope :described, -> {
    joins(:project_versions).merge(ProjectVersion.only_gemfile)
  }

  scope :vulnerable_project, -> {
    joins(:project_versions).merge(ProjectVersion.vulnerable)
  }

  #scope :production, -> { joins(:project_versions).merge(ProjectVersion.production).uniq }

  # 許可するカラムの名前をオーバーライドする
  def self.ransackable_attributes(auth_object = nil)
    %w(name)
  end

  # 依存情報を登録する
  def self.create_runtime_dependencies
    self.all.each do |plugin|
      # gem名を取得
      plugin.create_runtime_dependency
    end
    return true
  end

  def create_runtime_dependency
    result = Gems.dependencies([name])
    return unless result
    entries.each do |entry|
      #return if entry.dependencies.present?
      hash = result.find {|h| h[:number] == entry.version && h[:platform] == 'ruby' }
      # もしdependenciesが空であればリターン
      next unless hash
      next if hash[:dependencies].blank?
      hash[:dependencies].each do |target|
        plugin = Plugin.find_by(name: target[0])
        if plugin
          # 存在しなかったpluginが後から登録された場合
          dep = entry.dependencies.where(
                                requirements: target[1],
                                provisional_name: plugin.name).first
          if dep
            dep.provisional_name = nil
            dep.plugin = plugin
          else
            dep = entry.dependencies.where(
                                requirements: target[1],
                                provisional_name: nil,
                                plugin: plugin).first_or_initialize
          end

        else
          # 登録されていないgemの場合

          # 存在したpluginが後から削除された場合は、dependencyも自動的に削除されるが、
          # 再びこれを実行すると登録される。
          dep = entry.dependencies.where(
                                requirements: target[1],
                                provisional_name: target[0]).first_or_initialize
        end
        dep.save! if dep.changed?

        if plugin
          # latest_entry_in_requirementとdependencyは1対1の関係
          latest = LatestEntryInRequirement.find_or_initialize_by(dependency: dep)
          # requirementsで最新のentry_idを登録する
          latest.entry = dep.latest_version_in_requirements
          latest.save! if latest.changed?
        end

      end
    end

  rescue => e
    CronLog.error_create(
      table_name: 'dependency',
      content: "メソッド:create_runtime_dependency plugin: #{self && self.name} 詳細:#{e}"
    )
  end

  # Gemの情報を代入する
  def get_gem_uri
    gem_info = Gems.info(name)
    if gem_info.is_a?(Hash)
      path = gem_info['source_code_uri'].presence || gem_info['homepage_uri']
      self.source_code_uri = add_trailing_slash(path) if path.present?
      self.homepage_uri = gem_info['homepage_uri']
      # rubygemであるフラグを付ける
    else
      # rubygemに登録されていないplugin処理
    end
  end

  def update_dependencies
    if dependencies.present?
      dependencies.each do |dependency|
        dependency.provisional_name = self.name
        dependency.save
      end
    end
  end

  private

    # trailing slashを追加する
    def add_trailing_slash(path)
      # TODO: trailing slashを常に付ける方法が分からない
      path += '/' if path && path.last != '/'
      path
    end

# コールバック

  # def destroy_relatitons
  #   #gemの関連するもの削除する
  #   if dependency.present?
  #     dependency.destroy
  #   end
  #   if project_versions.present?
  #     project_versions.destroy_all
  #   end
  #   return true
  # end

  # 新規gem作成ログ
  def create_created_table_log
    CronLog.success_table(self.class.to_s.underscore, name, :create)
  end

  # 更新ログ
  def create_updated_table_log
    CronLog.success_table(self.class.to_s.underscore, name, :update)
  end

  # 削除ログ
  def create_destroyed_table_log
    CronLog.success_table(self.class.to_s.underscore, name, :delete)
  end


end

app/controllers/plugins_controller.rb
class PluginsController < ApplicationController
  before_action :set_plugin, only: [:show]

  # gem詳細画面
  def show
    @release_feeds = @plugin.entries.order('published desc').limit(5)
    @vulnerable_securities = @plugin.security_advisories.order('date desc')
  end

  private
  def set_plugin
    @plugin = Plugin.find(params[:id])
  end

end

app/views/plugins/_form.html.erb
<h2 class="ui header">
  <%= @plugin.name %> 設定情報の確認・変更
  <div class="sub header">ソースコードURLを手動で登録できます。</div>
</div>
</h2>
<br />

<% if @plugin.errors.any? %>
    <div class="ui error message">
      <i class="close icon"></i>
      <div class="header">
        不正な入力があります。
      </div>
      <ul class="list">
        <% @plugin.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="ui form">

  <%= form_for @plugin do |f| %>

    <div class="field">
      <label>
        ソースコードURL
        <i class="help large circle icon blue" id="help_source_code_uri" data-content="このGemのリリースフィードやCHANGELOG情報を取得するのに必要なURLです。"></i>
      </label>
      <%= f.text_field :source_code_uri, placeholder: 'http://github.com/example/example/', class: '' %>
    </div>

    <div class="field">
      <%= link_to plugin_path(@plugin), class: "ui button" do %>
        <i class="chevron left icon"></i> 詳細画面に戻る
      <% end %>
      <%= f.submit class: "ui orange button" %>
    </div>

      <%#= link_to 'クリア', projects_path, class: 'ui button' %>

  <% end %>
</div>

app/views/plugins/edit.html.erb
<%= render 'form' %>

app/views/plugins/index.html.erb
<h2 class="ui header">Gem</h2>

<div class="ui form">
  <%= search_form_for @search, url: plugins_path do |f| %>
    <div class="inline fields">
      <div class="field">
        <%= f.text_field :name_start, placeholder: 'Gem Name', class: '' %>
      </div>
      <div class="field">
        <%= f.select :projects_id_eq, Project.all.map{|p| [p.name, p.id]}, { include_blank: "すべてのプロジェクト" }, { class: 'ui dropdown' } %>
      </div>
      <%= f.submit '検索', class: "ui olive button" %>
      <%= link_to 'クリア', plugins_path, class: 'ui button' %>
    </div>
  <% end %>
</div>

<table class="ui celled table">
  <thead>
    <tr>
    <th>Gem</th>
    <th>リリースFeed数</th>
    <th>セキュリティFeed数</th>
    <th>プロジェクト</th>
    <th></th>
    </tr>
  </thead>
  <tbody>
  <% @plugins.each do |plugin| %>
    <tr>
      <td><%= plugin.name %></td>
      <td class="right aligned">
        <%= plugin.entries.count if plugin.entries.count > 0 %>
      </td>
      <td class="right aligned">
        <%= plugin.security_entries.count if plugin.security_entries.count > 0 %>
      </td>
      <td width="50%">
        <% plugin.projects.each do |project| %>
          <%= link_to(project_path(project.id), class: 'item') do %>
            <div class="ui small label">
              <%= project.name %>
            </div>
          <% end %>
        <% end %>
      </td>
      <td><%= link_to '詳細', plugin_path(plugin.id), class: "ui button" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<p>
  <%= page_entries_info @plugins %>
</p>
<%= paginate @plugins %>

app/views/plugins/show.html.erb
<div class="ui grid">

  <div class="column">
    <div class="ui message">
      <h1><%= @plugin.name %> 詳細情報</h1>
    </div>
  </div>

</div><!-- grid -->

<div class="ui grid">

  <div class="six wide column">
    <%= render partial: 'shared/latest_versions',
      locals: { release_feeds: @release_feeds, plugin: @plugin } %>

    <div class="ui segment">
      <h2><i class="folder open icon"></i>使用中のプロジェクト</h2>
      <div class="ui relaxed list">
        <% @plugin.project_versions.each do |version| %>
          <div class="item">
            <i class="large folder outline middle aligned icon"></i>
            <div class="content">
              <span class="header">
                <%= link_to version.project.name, project_path(version.project.id) %>
                <span style="<%= 'color:red;' if version.newest %>"><%= version.installed %></span>
              </span>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="ui segment">
      <h2><i class="external icon"></i>外部リンク</h2>
      <%= link_to @plugin.homepage_uri || "#{Settings.feeds.rubygem}#{@plugin.name}", class: "", target: '_blank' do %>
        <i class="external icon"></i>公式ホームページ
      <% end %>
    </div>

  </div>

  <div class="ten wide column">

    <div class="ui segment red">
      <h2><i class="warning sign icon red"></i>脆弱性情報履歴</h2>

      <div class="ui relaxed list">
        <% if @vulnerable_securities.empty? %>
          脆弱性情報は1件もありません。
        <% end %>
        <% @vulnerable_securities.each do |topic| %>
          <%= render partial: '/versions/security', locals: { topic: topic } %>
        <% end %>
      </div>

    </div>

  </div>


</div><!-- grid -->