config/routes.rb
Rails.application.routes.draw do

  root 'feeds#index'

  resources :feeds, only: [:index]

  resources :projects, only: [:index, :show, :edit, :update]

  resources :plugins, only: [:show] do
    resources :versions, only: [:index, :show]
  end

  resources :cron_logs, only: [:index]

  resources :abouts, only: [:index]

end

app/models/cron_log.rb
# == Schema Information
#
# Table name: cron_logs
#
#  id         :integer          not null, primary key
#  table_name :string
#  content    :text
#  state      :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

# cronのログ保存用テーブル
class CronLog < ActiveRecord::Base

  # ログ種別
  enum state: {
    success: 0,
    error:   1
  }

  # エラーログを作成する
  def self.error_create(attributes={})
    create!({ state: states[:error] }.merge(attributes))
    logger.error attributes[:content]
  end

  # 成功ログを作成する
  # def self.success_create(attributes={})
  #   create!({ state: states[:success] }.merge(attributes))
  #   logger.error attributes[:content]
  # end

  # テーブル操作ログを作成する
  def self.success_table(table, name, action)
    case action
    when :create; action_name = '作成'
    when :update; action_name = '更新'
    when :delete; action_name = '削除'
    end
    create!({
      state: states[:success],
      table_name: table ,
      content: "#{ I18n.t "activerecord.models.#{table}" }「#{ name }」が#{action_name}されました。"
    })
  end


end

app/controllers/cron_logs_controller.rb
class CronLogsController < ApplicationController

  # ログ一覧画面
  def index
    @search = CronLog.all.ransack(params[:q])
    @logs = @search.result.order('created_at desc').page(params[:page])
  end
end

app/helpers/cron_logs_helper.rb
module CronLogsHelper

  # 検索セレクトボックス テーブル一覧を表示する
  def table_lists
    ['project', 'plugin', 'entry', 'security_advisory', 'dependency', 'project_version'].map do | table |
      [ t("activerecord.models.#{table}"), table ]
    end
  end


end

app/views/cron_logs/index.html.erb
<h2 class="ui header">
  ログ
</h2>
<div class="sub header">
  DB処理やエラーのログ一覧。
  <ul style="list-style:none;">
    <li>※ リリースフィードの追加ログは出ません。</li>
    <li>※ プロジェクトのそれぞれのgem(version)の追加・更新・削除のログは出ません。</li>
  </ul>
</div>

<div class="ui form">
  <%= search_form_for @search, url: cron_logs_path do |f| %>
    <div class="inline fields">
      <div class="field">
        <div class="ui radio checkbox">
          <%= f.radio_button :state_eq, 1 %>
          <%= f.label :state_eq_1, 'エラーログのみ' %>
        </div>
      </div>
      <div class="field">
        <div class="ui radio checkbox">
         <%= f.radio_button :state_eq, 0 %>
          <%= f.label :state_eq_0, '成功ログのみ' %>
        </div>
      </div>
      <div class="field">
        <div class="ui radio checkbox">
         <%= f.radio_button :state_eq, '' %>
          <%= f.label :state_eq_, 'すべて' %>
        </div>
      </div>
      <div class="field">
        <%= f.select :table_name_eq, table_lists, { include_blank: "すべて" }, { class: 'ui dropdown' } %>
      </div>
      <%= f.submit '検索', class: "ui olive button" %>
      <%= link_to 'クリア', cron_logs_path, class: 'ui button' %>
    </div>
  <% end %>
</div>

<table class="ui celled table">
  <thead>
    <tr>
    <th>発生箇所(テーブル)</th>
    <th>種別</th>
    <th class="">内容</th>
    <th>作成日</th>
    </tr>
  </thead>
  <tbody>
  <% @logs.each do |log| %>
    <tr class="<%= log.state %>">
      <td><%= t "activerecord.models.#{log.table_name}" %></td>
      <td><%= log.state %></td>
      <td><%= log.content %></td>
      <td><%= l log.created_at %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<p><%= page_entries_info @logs %></p>
<%= paginate @logs %>