config/routes.rb
Rails.application.routes.draw do

  root 'feeds#index'

  resources :feeds, only: [:index]

  resources :projects, only: [:index, :show, :edit, :update]

  resources :plugins, only: [:show] do
    resources :versions, only: [:index, :show]
  end

  resources :cron_logs, only: [:index]

  resources :abouts, only: [:index]

end

app/models/project.rb
# -*- coding: utf-8 -*-
# == Schema Information
#
# Table name: projects
#
#  id                :integer          not null, primary key
#  name              :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  gitlab_id         :integer
#  http_url_to_repo  :string           default(""), not null
#  ssh_url_to_repo   :string           default(""), not null
#  commit_id         :string
#  gemfile_content   :text
#  web_url           :string
#  description       :text
#  gitlab_created_at :datetime
#  gitlab_updated_at :datetime
#

require "open3"

class Project < ActiveRecord::Base
  include DisplayVersion

  has_many :plugins, through: :project_versions
  has_many :project_versions, dependent: :destroy

  accepts_nested_attributes_for :project_versions, allow_destroy: true,
                                 reject_if: :all_blank

  validates :name, presence: true
  validates :name, length: { maximum: 50 }, allow_blank: true
  validates :name, format: { with: /\A[a-z0-9_-]+\z/i }, allow_blank: true


  #validate :exist_project

  # validates :description, length: { maximum: 500 }, allow_blank: true

  # validates :web_url, presence: true
  # validates :web_url, length: { maximum: 200 }, allow_blank: true
  # validates :web_url, format: /\A#{URI::regexp(%w(http https))}\z/, allow_blank: true

  # validates :http_url_to_repo, presence: true
  # validates :http_url_to_repo, length: { maximum: 200 }, allow_blank: true
  # validates :http_url_to_repo, format: /\A#{URI::regexp(%w(http https))}\z/, allow_blank: true

  # # TODO: ちゃんとした正規表現に修正したい
  # validates :ssh_url_to_repo, presence: true
  # validates :ssh_url_to_repo, length: { maximum: 200 }, allow_blank: true
  # validates :ssh_url_to_repo, format: /\Agit\@\S+\/\S+\.git\z/, allow_blank: true

  after_create :create_created_table_log
  after_update :create_updated_table_log

  # 脆弱性情報があるプロジェクトを上にする
  scope :security_order, ->(ids) {
    if ids.present?
      values = "(#{ids.join(',')})"
      order("CASE WHEN id IN #{values} THEN 1 ELSE 0 END DESC, gitlab_created_at DESC")
    else
      order("gitlab_created_at DESC")
    end
  }

  # project plugin entry project_version 更新
  def self.update_projects
    Project.all.each do |project|
      begin
        if project.updated_gemfile?
          project.update_gemfile               # git pull
          project.generate_gemfile_lock        # bundle install
          project.update_plugins_and_versions  # bundle list
        end
        if project.has_gemfile_in_remote?
          project.update_versions              # bundle outdated
        end
      rescue Gitlab::Error::Forbidden => e
        CronLog.error_create(
          table_name: self.class.to_s.underscore,
          content: "メソッド:add_projects 詳細:#{e}"
        )
      rescue StandardError => e
        CronLog.error_create(
          table_name: self.class.to_s.underscore,
          content: "メソッド:update_projects 詳細:#{e}"
        )
      end
    end
  end

  # GitLabで新しく追加されたプロジェクトを管理下に追加
  def self.add_projects(option={})
    projects = gitlab_projects
    projects.sort_by! {|p| p.id } if option[:sort] #(&:id)
    projects.each do |project|
      begin
        result = Project.find_by(gitlab_id: project.id)
        unless result
          model = Project.new(
            name:              project.name,
            gitlab_id:         project.id,
            http_url_to_repo:  project.http_url_to_repo,
            ssh_url_to_repo:   project.ssh_url_to_repo,
            web_url:           project.web_url,
            description:       project.description,
            gitlab_created_at: project.created_at,
            gitlab_updated_at: project.last_activity_at
          )
          has_gemfile = model.has_gemfile_in_remote?
          model.gemfile_content = model.newest_gemfile if has_gemfile
          model.commit_id = model.gitlab_commit_id
          model.save!

          model.generate_project_files        # git clone(mkdir + copy Gemfile)
          if has_gemfile
            model.generate_gemfile_lock       # bundle install
            model.create_plugins_and_versions # bundle list
            model.update_versions             # bundle outdated
          end
        end
      rescue Gitlab::Error::Forbidden => e
        CronLog.error_create(
          table_name: self.class.to_s.underscore,
          content: "メソッド:add_projects 詳細:#{e}"
        )
      rescue => e
        CronLog.error_create(
          table_name: self.class.to_s.underscore,
          content: "メソッド:add_projects 詳細:#{e}"
        )
      end
    end
  end

  # 許可するカラムの名前をオーバーライドする
  def self.ransackable_attributes(auth_object = nil)
    %w(id name)
  end

  # 許可する関連の配列をオーバーライドする
  def self.ransackable_associations(auth_object = nil)
    reflect_on_all_associations.map { |a| a.name.to_s }
  end

  def self.ransackable_scopes(auth_object = nil)
    %i[]
  end

  # Gemfileがあるプロジェクトか調べる(ローカル)
  # def has_gemfile?
  #   File.exist?("#{Rails.root}/#{Settings.path.working_directory}/#{name}/Gemfile")
  # end

  # Gemfileがあるプロジェクトか調べる(リモート)
  def has_gemfile_in_remote?
    exist_file?('Gemfile')
  end

  # Gemfile.lockがあるプロジェクトか調べる(リモート)
  def has_gemfile_lock_in_remote?
    exist_file?('Gemfile.lock')
  end

  # projectのディレクトリ、Gemfile、Gemfile.lockを作成
  def generate_project_files
    path = "#{Rails.root}/#{Settings.path.working_directory}"
    Dir.chdir(path) do
      run("mkdir #{name}") unless Dir.exist?("name")
    end
    Dir.chdir("#{path}/#{name}") do
      if has_gemfile_in_remote?
        gemfile = File.open('Gemfile', "w") do |file|
          file.print(newest_gemfile)
        end
        # engine gemをコメントアウトする
        comment_gems_with_path_option
      end
      if has_gemfile_lock_in_remote?
        File.open('Gemfile.lock', "w") do |file|
          file.print(newest_gemfile_lock)
        end
      end
    end
  end

  # Gemfile、Gemfile.lockを更新する(git pullは使わない)
  def update_gemfile
    Dir.chdir("#{Rails.root}/#{Settings.path.working_directory}/#{name}") do
      if has_gemfile_in_remote?
        gemfile = File.open('Gemfile', "w+") do |file|
          file.print(newest_gemfile)
        end
        # engine gemをコメントアウトする
        comment_gems_with_path_option
      end
      if has_gemfile_lock_in_remote?
        File.open('Gemfile.lock', "w") do |file|
          file.print(newest_gemfile_lock)
        end
      end
      #run("git pull origin master")
    end
    self.update(
      gemfile_content: newest_gemfile,
      commit_id:       gitlab_commit_id,
      gitlab_updated_at: get_gitlab_updated_at
    )
  end

  # bundle install コマンド
  # Gemfile.lockを作成する(productionのみ取り出すため)
  def generate_gemfile_lock
    Dir.chdir("#{Rails.root}/#{Settings.path.working_directory}/#{name}") do
      Bundler.with_clean_env do
        result = run("bundle install --path vendor/bundle --without development test")
        # エラーチェック
        unless result.include? 'Bundle complete!'
          message = ''
          if result =~ /An\serror\soccurred\swhile\sinstalling/
            message = $'
          end
          raise "bundle install でエラーが発生しました。=> #{message}"
        end
      end
    end
  end

  # bundle list コマンド
  # 新しいgemが追加されたら、project_version追加(plugin、entryがなければ作成)
  def create_plugins_and_versions
    gemfile_gems = gemfile_list
    path = "#{Rails.root}/#{Settings.path.working_directory}/#{name}"
    Dir.chdir(path) do
      Bundler.with_clean_env do

        result = run("bundle list")
        # エラーチェック
        if result.include? "Could not find"
          raise "bundle list でエラーが発生しました。=> #{result}"
        end
        result.each_line do |line|
          if line.start_with?('  * ')
            value = line.scan(/\s\s\*\s(\S+)\s\((.+)\)/).flatten

            new_plugin = Plugin.find_or_initialize_by(name: value[0])
            # gem情報更新
            new_plugin.get_gem_uri# if valid_plugin_format?
            # p new_plugin.name
            new_plugin.save! if new_plugin.changed?

            # TODO:
            Entry.update_list(new_plugin)
            version_value = split_version(value[1])
            entry = new_plugin.entries.where(major_version: version_value[0],
                                             minor_version: version_value[1],
                                             patch_version: version_value[2],
                                             revision_version: version_value[3]
            ).first

            project_versions.create!(installed: value[1],
                                     plugin:    new_plugin,
                                     entry:     entry,
                                     described: gemfile_gems.include?(value[0])
            )
          end
        end
      end
    end
  end

  # bundle list コマンド
  # 新しいgemが追加されたら、project_version追加(plugin、entryがなければ作成)
  # 既存のgemが削除されたら、project_version削除(versionが1件もなくなればplugin削除)
  def update_plugins_and_versions
    gemfile_gems = gemfile_list
    path = "#{Rails.root}/#{Settings.path.working_directory}/#{name}"
    Dir.chdir(path) do
      Bundler.with_clean_env do
        result = run("bundle list")
        # エラーチェック
        if result.include? "Could not find"
          raise "bundle list でエラーが発生しました。=> #{result}"
        end
        names = []
        # 新規gemがあれば追加する
        result.each_line do |line|
          if line.start_with?('  * ')
            value = line.scan(/\s\s\*\s(\S+)\s\((.+)\)/).flatten

            version = project_versions.joins(:plugin).where('plugins.name' => value[0]).first
            if version
              # installedのみ更新、他は初期化(update_versionsで取得し直す)
              version.update(installed: value[1],
                             newest:    nil,
                             requested: nil,
                             described: gemfile_gems.include?(value[0])
              )
            else
              new_plugin = Plugin.find_or_initialize_by(name: value[0])
              # gem情報更新

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :set_project, only: [:show, :edit, :update]
  before_action :check_updatable, only: [:edit, :update]

  # プロジェクト一覧画面
  def index
    # 脆弱性情報のあるproject_ids
    @security_alert_ids = []
    Project.all.each do |project|
      @security_alert_ids << project.id if project.has_security_alert?
    end

    @search = Project.security_order(@security_alert_ids).ransack(params[:q])
    @projects = @search.result.page(params[:page])
  end

  # プロジェクト詳細画面
  def show
    # TODO: ransackに変えたい(ransackのradioボタン検索が難しい)
    @form = PluginForm.new(form_params)
    @plugins = @form.search_by_project(@project)
  end

  # プロジェクト編集画面
  def edit
  end

  # プロジェクト更新
  def update
    # TODO: entryに紐づけないといけない!!
    if @project.update_attributes(project_params_for_update)
      redirect_to @project, notice: '正しく更新されました。'
    else
      render action: :edit
    end
  end

  private
  def set_project
    @project = Project.find(params[:id])
  end

  # 更新可能なプロジェクトか確認する
  # Gemfile情報を持っているprojectは更新できない
  def check_updatable
    if @project.gemfile_content
      flash[:alert] = 'このプロジェクトは画面から更新できません。'
      redirect_to @project
    end
  end

  def form_params
    if params[:plugin_form]
      params[:plugin_form].permit(:name, :updated)
    else
      { updated: '1' }
    end
  end

  def project_params_for_update
    params.require(:project).permit(
      project_versions_attributes: [ :id, :project_id, :installed, :requested, :plugin_name, :described, :_destroy]
    )
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper

  # 行を削除する
  def link_to_remove_field(name, f)
    f.hidden_field(:_destroy) +
    link_to("#", { onclick: "remove_fields(this)", class: "ui button red" }) do
      raw(name)
    end
  end

  # 行を追加する
  def link_to_add_fields(name, f, association, target)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to "#", { onclick: %Q[add_fields(this, "#{association}", "#{escape_javascript(fields)}", "#{target}")], class: "ui button right floated" } do
      raw(name)
    end
  end

end

app/views/projects/_form.html.erb
<% if @project.errors.any? %>
  <div class="ui error message">
    <i class="close icon"></i>
    <div class="header">
      不正な入力があります。
    </div>
    <ul class="list">
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="ui form">
  <%= form_for @project do |f| %>

  <% if f.object.new_record? %>
    <div class="field">
      <label>プロジェクト名</label>
      <%= f.text_field :name, placeholder: '', class: '' %>
    </div>
  <% end %>

  <% if false %>
    <div class="field">
      <label>プロジェクト説明</label>
      <%= f.text_area :description, placeholder: '', class: '' %>
    </div>

    <div class="field">
      <label>WEBサイトURL</label>
      <%= f.text_field :web_url, placeholder: 'http://example.com/project', class: '' %>
    </div>
    <div class="field">
      <label>リポジトリURL(HTTP)</label>
      <%= f.text_field :http_url_to_repo, placeholder: 'http://example.com/project.git', class: '' %>
    </div>
    <div class="field">
      <label>リポジトリURL(SSH)</label>
      <%= f.text_field :ssh_url_to_repo, placeholder: 'git@example.com/project.git', class: '' %>
    </div>
  <% end %>

    <h3 class="ui header">
      Gem
      <div class="sub header">
       Gemfileがないプロジェクトの場合のみ入力してください。
      </div>
    </h3>

    <div class="field">
      <table class="ui table">
        <thead>
          <tr>
            <th>Gem名</th>
            <th>バージョン</th>
            <th>バージョン固定</th>
            <th>Gemfile</th>
            <th></th>
          </tr>
        </thead>
        <tbody id="project_versions">
          <%= f.fields_for :project_versions do |lf| %>
            <%= render partial: 'project_version_fields', locals: { f: lf } %>
          <% end %>
        </tbody>
      </table>
      <p>
        <%= link_to_add_fields "行追加", f, :project_versions, "#project_versions" %>
      </p>
    </div>

    <div class="field">
      <% if @project.persisted? %>
        <%= link_to project_path(@project), class: "ui button" do %>
          <i class="chevron left icon"></i> 詳細画面に戻る
        <% end %>
      <% end %>
      <%= f.submit class: "ui orange button" %>
    </div>

  <% end %>
</div>

app/views/projects/_project_version_fields.html.erb
<tr class="rows">
  <%= f.hidden_field :id %>
  <%# plugin_idを持っているため、plugin_nameは変更はできない %>
  <td><%= f.text_field :plugin_name, placeholder: '', class: '', maxlength: '50', disabled: f.object.persisted? %></td>
  <td><%= f.text_field :installed, placeholder: '1.2.3', class: '', maxlength: '20', disabled: f.object.persisted? %></td>
  <td><%= f.text_field :requested, placeholder: '= 1.0', class: '', maxlength: '20' %></td>
  <td class="center aligned">
    <%= f.hidden_field :described, { value: false } %>
    <%= f.check_box :described, { class: "ui checkbox" }, true, false %>
  </td>
  <td>
    <%= link_to_remove_field "削除", f %>
  </td>
</tr>

app/views/projects/edit.html.erb
<h2 class="ui header">
  <%= @project.name %> プロジェクト設定情報の確認・変更
  <div class="sub header">
    プロジェクトを編集できます。(Gemfileがないプロジェクトのみ)
    GemにおいてGitLabと同期していないので注意。
  </div>
</h2>
<br />

<%= render 'form' %>

app/views/projects/index.html.erb
<h2 class="ui header">プロジェクト</h2>

<div class="ui form">
  <%= search_form_for @search, url: projects_path do |f| %>
    <div class="inline fields">
      <div class="field">
        <%= f.text_field :name_start, placeholder: 'プロジェクト名', class: '' %>
      </div>
      <%= f.submit '検索', class: "ui olive button" %>
      <%= link_to 'クリア', projects_path, class: 'ui button' %>
    </div>
  <% end %>
</div>

<table class="ui celled table">
  <thead>
    <tr>
    <th>プロジェクト名</th>
    <th>Gemfile Gems</th>
    <th>Dependency Gems</th>
    <th>更新可能なGems(Gemfile Gems)</th>
    <th>脆弱性</th>
    <th>作成日</th>
    <th></th>
    </tr>
  </thead>
<tbody>
<% @projects.each do |project| %>
  <tr>
    <td><%= project.name %></td>
    <td class="right aligned">
      <%= project.project_versions.only_gemfile.count %>
    </td>
    <td class="right aligned">
      <%= project.project_versions.no_gemfile.count %>
    </td>
    <td class="right aligned">
      <%= project.project_versions.only_gemfile.newest_versions.count %>
    </td>
    <td class="center aligned">
      <% if @security_alert_ids.include?(project.id) %>
        <i class="warning sign icon red"></i>
      <% end %>
    </td>
    <td><%= l(project.gitlab_created_at, format: :date) if project.gitlab_created_at %></td>
    <td class="center aligned">
      <%= link_to '詳細', project_path(project.id), class: "ui small button" %>
    </td>
  </tr>
<% end %>
</tbody>
</table>

<p>
  <%= page_entries_info @projects %>
</p>
<%= paginate @projects %>

<% if false %>
  <%= link_to 'プロジェクトの登録', new_project_path, class: 'ui primary button right floated', style: 'color:red' %>
<% end %>

app/views/projects/new.html.erb
<h2 class="ui header">
  プロジェクトの新規登録
  <div class="sub header">GitLabのプロジェクトを登録します。</div>
</h2>
<br />

<%= render 'form' %>

app/views/projects/show.html.erb
<div class="ui message">
  <h1><%= @project.name %> プロジェクト詳細情報</h1>
  <p><%= @project.description %></p>
  <%= link_to @project.web_url, class: "ui blue button", target: '_blank' do %>
    GitLabページへ <i class="chevron right icon"></i>
  <% end %>
  <% unless @project.gemfile_content %>
    <%= link_to edit_project_path(@project), class: "ui orange button" do %>
      設定確認・変更 <i class="chevron right icon"></i>
    <% end %>
  <% end %>
</div>

<h2 class="ui header">Gem</h2>
<div class="ui form">

  <%= form_for @form, url: project_path(@project), method: :get do |f| %>
    <div class="inline fields">
      <div class="field">
        <%= f.text_field :name, placeholder: "Gem Name" %>
      </div>
      <div class="field">
        <div class="ui radio checkbox">
          <%= f.radio_button :updated, 1 %>
          <%= f.label :updated_1, '更新可能' %>
        </div>
      </div>
      <div class="field">
        <div class="ui radio checkbox">
         <%= f.radio_button :updated, 2 %>
          <%= f.label :updated_2, '更新済み' %>
        </div>
      </div>
      <div class="field">
        <div class="ui radio checkbox">
          <%= f.radio_button :updated, 0 %>
          <%= f.label :updated_0, 'すべて' %>
        </div>
      </div>

      <div class="field">
        <%= f.submit '検索', class: 'ui olive button' %>
        <%= link_to 'クリア', project_path(@project), class: 'ui button' %>
      </div>
    </div>
  <% end %>
</div>

<table class="ui celled table">
  <thead>
    <tr>
      <th>Gem</th>
      <th>最新のバージョン</th>
      <th>現在のバージョン</th>
      <th>固定</th>
      <th class="four wide column">脆弱性情報(依存先含む)</th>
    </tr>
  </thead>
  <tbody>
    <% @plugins.each do |version| %>
      <%# TODO: 改善必要 %>
      <% target_versions = version.security_check %>
      <% state = 'negative' if target_versions.present? %>
      <tr class="<%= state %>">
        <td><%= version.plugin.name %></td>
        <td><%= version.newest %></td>
        <td><%= link_to version.installed, plugin_version_path(plugin_id: version.plugin.id, id: version.entry.id) %></td>
        <td><%= version.requested %></td>
        <td>
          <% target_versions.each do |target| %>
            <%= link_to plugin_version_path(plugin_id: target.plugin.id, id: target.entry.id) do %>
              <div class="ui small label red">
                <%= target.plugin.name %>
                <%= target.installed %>
              </div>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>